In [1]:
import torch

In [2]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [9]:
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        print(f'{x_i} . {x_j} = {torch.dot(x_i,x_j)}')

tensor([0.4300, 0.1500, 0.8900]) . tensor([0.4300, 0.1500, 0.8900]) = 0.9994999170303345
tensor([0.4300, 0.1500, 0.8900]) . tensor([0.5500, 0.8700, 0.6600]) = 0.9544000625610352
tensor([0.4300, 0.1500, 0.8900]) . tensor([0.5700, 0.8500, 0.6400]) = 0.9422000050544739
tensor([0.4300, 0.1500, 0.8900]) . tensor([0.2200, 0.5800, 0.3300]) = 0.47530001401901245
tensor([0.4300, 0.1500, 0.8900]) . tensor([0.7700, 0.2500, 0.1000]) = 0.4575999975204468
tensor([0.4300, 0.1500, 0.8900]) . tensor([0.0500, 0.8000, 0.5500]) = 0.6310000419616699
tensor([0.5500, 0.8700, 0.6600]) . tensor([0.4300, 0.1500, 0.8900]) = 0.9544000625610352
tensor([0.5500, 0.8700, 0.6600]) . tensor([0.5500, 0.8700, 0.6600]) = 1.4950001239776611
tensor([0.5500, 0.8700, 0.6600]) . tensor([0.5700, 0.8500, 0.6400]) = 1.4754000902175903
tensor([0.5500, 0.8700, 0.6600]) . tensor([0.2200, 0.5800, 0.3300]) = 0.8434000015258789
tensor([0.5500, 0.8700, 0.6600]) . tensor([0.7700, 0.2500, 0.1000]) = 0.7070000171661377
tensor([0.5500, 0.87